before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}

sboms:
  - artifacts: archive

archives:
- format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'sha256sums.txt'

changelog:
  skip: true

brews:
  - tap:
      owner: nginxinc
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://www.nginx.com/
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    install: |
      bin.install "nginx-prometheus-exporter"
    commit_author:
      name: nginx-bot
      email: kubernetes@nginx.com
